site_name: AcWiki 大学生的百科全书
site_url: https://ztm0929.github.io/AcWiKi/ # 预览站点链接，合并成功后需要切换为主仓库链接
site_description: 属于大学生群体的真·青年大学习
repo_name: AcWiki
repo_url: https://github.com/Ac-Wiki/AcWiKi
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 <a href="https://github.com/Ac-Wiki/AcWiKi/" target="_blank">AcWiki</a>

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.footer
    - content.action.edit # source edit
    - content.action.view # source view
    - navigation.instant # Instant navigation
    #- navigation.tabs 后续可考虑启用
    #- navigation.tabs.sticky
    - toc.follow # Follow TOC
    - navigation.top # Top navigation
  palette:
    # match system theme color
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/AcWiki
      name: Telegram 频道
    - icon: simple/telegram
      link: https://t.me/AcFourm
      name: Telegram 群组

extra_javascript:
  - js/extra.js

plugins:
  - search
  - git-revision-date-localized: # commit/Modify date
      timezone: Asia/Shanghai
      enable_creation_date: true
  - git-authors: # git authors
      show_email_address: false
  - glightbox: # lightbox
      touchNavigation: true
      loop: true
      effect: none
      slide_effect: fade
      width: auto
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: false
      manual: false
